#docker-compose.yml
services:
  backend:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=development
      - PORT=5002
      - FIREBASE_SERVICE_ACCOUNT_KEY_PATH=/app/service-account.json
      # Docker-specific environment variables for better connectivity
      - UV_THREADPOOL_SIZE=128
      # Network timeout configurations
      - HTTP_TIMEOUT=30000
      - WEBSOCKET_TIMEOUT=30000
      # WebSocket specific configuration
      - DEEPGRAM_USE_DOCKER_WORKAROUND=true
      # Redis configuration
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-your_redis_password}
      - CACHE_ENABLED=true
    volumes:
      - ./service-account.json:/app/service-account.json
    env_file: .env
    networks:
      - medusavr-network
    restart: always
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    platform: linux/arm64
    image: redis:7-alpine
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-your_redis_password}
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD:-your_redis_password}
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
    volumes:
      - redis_data:/data
    networks:
      - medusavr-network
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 3s
      retries: 5

  frontend:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VITE_API_URL: ""
        VITE_SOCKET_URL: ""
        VITE_FIREBASE_API_KEY: ${VITE_FIREBASE_API_KEY}
        VITE_FIREBASE_AUTH_DOMAIN: ${VITE_FIREBASE_AUTH_DOMAIN}
        VITE_FIREBASE_PROJECT_ID: ${VITE_FIREBASE_PROJECT_ID}
        VITE_FIREBASE_STORAGE_BUCKET: ${VITE_FIREBASE_STORAGE_BUCKET}
        VITE_FIREBASE_MESSAGING_SENDER_ID: ${VITE_FIREBASE_MESSAGING_SENDER_ID}
        VITE_FIREBASE_APP_ID: ${VITE_FIREBASE_APP_ID}
        VITE_FIREBASE_MEASUREMENT_ID: ${VITE_FIREBASE_MEASUREMENT_ID}
        VITE_CLOUDINARY_CLOUD_NAME: ${VITE_CLOUDINARY_CLOUD_NAME}
        VITE_CLOUDINARY_UPLOAD_PRESET: ${VITE_CLOUDINARY_UPLOAD_PRESET}
        VITE_APP_ENV: production
        AI_BEHAVIOR_PROMPT: ${AI_BEHAVIOR_PROMPT}
        NOWPAYMENTS_API_KEY: ${NOWPAYMENTS_API_KEY}
        NOWPAYMENTS_IPN_SECRET: ${NOWPAYMENTS_IPN_SECRET}
    ports:
      - "80:80"
    env_file: .env
    networks:
      - medusavr-network
    depends_on:
      backend:
        condition: service_healthy
      redis:
        condition: service_healthy
          
    restart: always

volumes:
  redis_data:
    driver: local

networks:
  medusavr-network:
    driver: bridge