export interface Trait {
  id: string;
  name: string;
}

export interface BroadTerm {
  id: string;
  name: string;
  traits: Trait[];
  color: string;
}

export const personaTerms: BroadTerm[] = [
  {
    id: "adventurous",
    name: "Adventurous",
    color: "bg-blue-500",
    traits: [
      { id: "curious", name: "Curious" },
      { id: "daring", name: "Daring" },
      { id: "explorer", name: "Explorer" },
      { id: "fearless", name: "Fearless" },
      { id: "independent", name: "Independent" },
      { id: "resourceful", name: "Resourceful" },
      { id: "spontaneous", name: "Spontaneous" },
      { id: "thrill-seeker", name: "Thrill-seeker" },
      { id: "wanderer", name: "Wanderer" },
      { id: "bold", name: "Bold" },
    ],
  },
  {
    id: "calm",
    name: "Calm",
    color: "bg-green-500",
    traits: [
      { id: "peaceful", name: "Peaceful" },
      { id: "serene", name: "Serene" },
      { id: "patient", name: "Patient" },
      { id: "relaxed", name: "Relaxed" },
      { id: "tranquil", name: "Tranquil" },
      { id: "composed", name: "Composed" },
      { id: "gentle", name: "Gentle" },
      { id: "mellow", name: "Mellow" },
      { id: "steady", name: "Steady" },
      { id: "unflappable", name: "Unflappable" },
    ],
  },
  {
    id: "creative",
    name: "Creative",
    color: "bg-purple-500",
    traits: [
      { id: "artistic", name: "Artistic" },
      { id: "imaginative", name: "Imaginative" },
      { id: "innovative", name: "Innovative" },
      { id: "inventive", name: "Inventive" },
      { id: "original", name: "Original" },
      { id: "visionary", name: "Visionary" },
      { id: "expressive", name: "Expressive" },
      { id: "resourceful", name: "Resourceful" },
      { id: "unique", name: "Unique" },
      { id: "inspired", name: "Inspired" },
    ],
  },
  {
    id: "energetic",
    name: "Energetic",
    color: "bg-yellow-500",
    traits: [
      { id: "lively", name: "Lively" },
      { id: "enthusiastic", name: "Enthusiastic" },
      { id: "spirited", name: "Spirited" },
      { id: "dynamic", name: "Dynamic" },
      { id: "vibrant", name: "Vibrant" },
      { id: "zealous", name: "Zealous" },
      { id: "animated", name: "Animated" },
      { id: "eager", name: "Eager" },
      { id: "driven", name: "Driven" },
      { id: "active", name: "Active" },
    ],
  },
  {
    id: "intellectual",
    name: "Intellectual",
    color: "bg-indigo-500",
    traits: [
      { id: "analytical", name: "Analytical" },
      { id: "logical", name: "Logical" },
      { id: "observant", name: "Observant" },
      { id: "rational", name: "Rational" },
      { id: "thoughtful", name: "Thoughtful" },
      { id: "wise", name: "Wise" },
      { id: "curious", name: "Curious" },
      { id: "inquisitive", name: "Inquisitive" },
      { id: "knowledgeable", name: "Knowledgeable" },
      { id: "reflective", name: "Reflective" },
    ],
  },
  {
    id: "kind",
    name: "Kind",
    color: "bg-pink-500",
    traits: [
      { id: "compassionate", name: "Compassionate" },
      { id: "empathetic", name: "Empathetic" },
      { id: "generous", name: "Generous" },
      { id: "gentle", name: "Gentle" },
      { id: "loving", name: "Loving" },
      { id: "nurturing", name: "Nurturing" },
      { id: "supportive", name: "Supportive" },
      { id: "understanding", name: "Understanding" },
      { id: "warm", name: "Warm" },
      { id: "altruistic", name: "Altruistic" },
    ],
  },
  {
    id: "mysterious",
    name: "Mysterious",
    color: "bg-gray-500",
    traits: [
      { id: "enigmatic", name: "Enigmatic" },
      { id: "secretive", name: "Secretive" },
      { id: "elusive", name: "Elusive" },
      { id: "cryptic", name: "Cryptic" },
      { id: "shadowy", name: "Shadowy" },
      { id: "unpredictable", name: "Unpredictable" },
      { id: "alluring", name: "Alluring" },
      { id: "reserved", name: "Reserved" },
      { id: "intriguing", name: "Intriguing" },
      { id: "hidden", name: "Hidden" },
    ],
  },
  {
    id: "playful",
    name: "Playful",
    color: "bg-red-500",
    traits: [
      { id: "amusing", name: "Amusing" },
      { id: "cheerful", name: "Cheerful" },
      { id: "jovial", name: "Jovial" },
      { id: "mischievous", name: "Mischievous" },
      { id: "witty", name: "Witty" },
      { id: "humorous", name: "Humorous" },
      { id: "lighthearted", name: "Lighthearted" },
      { id: "sprightly", name: "Sprightly" },
      { id: "frolicsome", name: "Frolicsome" },
      { id: "whimsical", name: "Whimsical" },
    ],
  },
  {
    id: "serious",
    name: "Serious",
    color: "bg-teal-500",
    traits: [
      { id: "solemn", name: "Solemn" },
      { id: "grave", name: "Grave" },
      { id: "earnest", name: "Earnest" },
      { id: "resolute", name: "Resolute" },
      { id: "thoughtful", name: "Thoughtful" },
      { id: "dignified", name: "Dignified" },
      { id: "focused", name: "Focused" },
      { id: "intense", name: "Intense" },
      { id: "purposeful", name: "Purposeful" },
      { id: "reserved", name: "Reserved" },
    ],
  },
  {
    id: "stoic",
    name: "Stoic",
    color: "bg-orange-500",
    traits: [
      { id: "resilient", name: "Resilient" },
      { id: "patient", name: "Patient" },
      { id: "enduring", name: "Enduring" },
      { id: "unemotional", name: "Unemotional" },
      { id: "calm", name: "Calm" },
      { id: "self-controlled", name: "Self-controlled" },
      { id: "steadfast", name: "Steadfast" },
      { id: "tolerant", name: "Tolerant" },
      { id: "unflinching", name: "Unflinching" },
      { id: "detached", name: "Detached" },
    ],
  },
];
