import React from 'react';
import LegalPolicyPage from '../../components/LegalPolicyPage';

const LiabilityDisclaimerPage: React.FC = () => {
  return (
    <LegalPolicyPage title="Liability Disclaimer & User Responsibility" lastUpdated="August 15, 2025">
      <div>
        <section className="mb-8">
          <div className="bg-red-900/30 border border-red-600 p-6 rounded-lg mb-6">
            <h2 className="text-2xl font-bold text-red-400 mb-4">⚠️ CRITICAL DISCLAIMER</h2>
            <p className="text-gray-200 text-lg font-semibold">
              BY USING MEDUSAVR, YOU ACKNOWLEDGE AND AGREE THAT YOU ARE SOLELY AND COMPLETELY RESPONSIBLE FOR ALL CONTENT YOU GENERATE, CREATE, OR INTERACT WITH ON THIS PLATFORM.
            </p>
          </div>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold text-white mb-4">1. COMPLETE USER RESPONSIBILITY</h2>
          <div className="bg-orange-900/20 border border-orange-700 p-6 rounded-lg space-y-4">
            <div>
              <h3 className="text-lg font-semibold text-orange-400 mb-3">Your Sole Responsibility</h3>
              <ul className="list-disc list-inside space-y-2 text-gray-300">
                <li><strong>ALL CONTENT:</strong> You are 100% responsible for every image, character, conversation, and piece of content you generate or create</li>
                <li><strong>LEGAL COMPLIANCE:</strong> You must ensure all your activities comply with applicable laws in your jurisdiction</li>
                <li><strong>AGE VERIFICATION:</strong> You are responsible for verifying your own age and eligibility to use adult content platforms</li>
                <li><strong>CONSENT:</strong> You are responsible for obtaining all necessary consents for any likeness or reference material you use</li>
                <li><strong>COPYRIGHT:</strong> You are responsible for ensuring you do not infringe on any copyrighted materials or intellectual property</li>
                <li><strong>CONSEQUENCES:</strong> You accept full legal and financial responsibility for any consequences of your actions on this platform</li>
              </ul>
            </div>
          </div>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold text-white mb-4">2. MEDUSAVR, RINTERIOR & TEAM DISCLAIMER</h2>
          <div className="bg-red-900/20 border border-red-700 p-6 rounded-lg space-y-4">
            <div>
              <h3 className="text-lg font-semibold text-red-400 mb-3">ZERO LIABILITY</h3>
              <div className="space-y-4">
                <div className="bg-red-800/30 border border-red-600 p-4 rounded">
                  <p className="text-gray-200 font-semibold mb-2">
                    MEDUSAVR, RINTERIOR, AND ALL TEAM MEMBERS, OWNERS, OPERATORS, EMPLOYEES, CONTRACTORS, AND AFFILIATES:
                  </p>
                  <ul className="list-disc list-inside space-y-1 text-gray-300 text-sm">
                    <li>ARE NOT RESPONSIBLE for any illegal content generated by users</li>
                    <li>ARE NOT LIABLE for any user's violation of laws or regulations</li>
                    <li>BEAR NO RESPONSIBILITY for copyright infringement by users</li>
                    <li>ARE NOT ACCOUNTABLE for any harmful or illegal activities conducted by users</li>
                    <li>HAVE NO LIABILITY for any legal consequences users may face</li>
                    <li>ARE NOT RESPONSIBLE for any damages, losses, or legal issues arising from user actions</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold text-white mb-4">3. PLATFORM LIMITATION OF LIABILITY</h2>
          <div className="bg-gray-800 border border-gray-600 p-6 rounded-lg space-y-4">
            <div>
              <h3 className="text-lg font-semibold text-gray-300 mb-3">Service Provision</h3>
              <ul className="list-disc list-inside space-y-2 text-gray-300">
                <li><strong>TOOL PROVISION ONLY:</strong> MEDUSAVR provides AI generation tools "AS IS" without any warranty</li>
                <li><strong>NO CONTENT CONTROL:</strong> We do not control what users choose to generate or create</li>
                <li><strong>NO MONITORING GUARANTEE:</strong> While we implement safety measures, we cannot guarantee detection of all problematic content</li>
                <li><strong>USER CHOICE:</strong> All content generation decisions are made solely by users</li>
                <li><strong>NO LEGAL ADVICE:</strong> We provide no legal advice or guidance on content legality</li>
              </ul>
            </div>
          </div>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold text-white mb-4">4. INDEMNIFICATION CLAUSE</h2>
          <div className="bg-yellow-900/20 border border-yellow-700 p-6 rounded-lg space-y-4">
            <div>
              <h3 className="text-lg font-semibold text-yellow-400 mb-3">User Indemnification Agreement</h3>
              <div className="bg-yellow-800/30 border border-yellow-600 p-4 rounded">
                <p className="text-gray-200 font-semibold mb-3">
                  BY USING MEDUSAVR, YOU AGREE TO INDEMNIFY, DEFEND, AND HOLD HARMLESS:
                </p>
                <ul className="list-disc list-inside space-y-2 text-gray-300">
                  <li>MEDUSAVR platform and all its services</li>
                  <li>RINTERIOR company and all subsidiaries</li>
                  <li>All owners, operators, team members, and employees</li>
                  <li>All contractors, affiliates, and business partners</li>
                  <li>All third-party service providers and partners</li>
                </ul>
                <p className="text-gray-200 font-semibold mt-4 mb-2">FROM ANY AND ALL:</p>
                <ul className="list-disc list-inside space-y-1 text-gray-300">
                  <li>Legal claims, lawsuits, or legal proceedings</li>
                  <li>Damages, losses, costs, or expenses</li>
                  <li>Attorney fees and legal costs</li>
                  <li>Regulatory fines or penalties</li>
                  <li>Criminal charges or investigations</li>
                  <li>Reputation damage or business losses</li>
                </ul>
                <p className="text-gray-200 font-semibold mt-4">
                  ARISING FROM YOUR USE OF THE PLATFORM OR CONTENT YOU GENERATE.
                </p>
              </div>
            </div>
          </div>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold text-white mb-4">5. ILLEGAL CONTENT DISCLAIMER</h2>
          <div className="bg-red-900/20 border border-red-700 p-6 rounded-lg space-y-4">
            <div>
              <h3 className="text-lg font-semibold text-red-400 mb-3">Zero Tolerance - User Responsibility</h3>
              <div className="space-y-3">
                <p className="text-gray-300">
                  <strong>IF ANY USER GENERATES, CREATES, OR ATTEMPTS TO CREATE ILLEGAL CONTENT:</strong>
                </p>
                <ul className="list-disc list-inside space-y-2 text-gray-300 pl-4">
                  <li>The user bears <strong>100% COMPLETE RESPONSIBILITY</strong></li>
                  <li>MEDUSAVR, RINTERIOR, and all team members bear <strong>ZERO RESPONSIBILITY</strong></li>
                  <li>All legal consequences fall solely on the user</li>
                  <li>All criminal liability belongs exclusively to the user</li>
                  <li>All financial penalties are the user's sole responsibility</li>
                  <li>We will cooperate fully with law enforcement against the user</li>
                </ul>
                <div className="bg-red-800/30 border border-red-600 p-3 rounded mt-4">
                  <p className="text-red-200 font-semibold">
                    ⚠️ WARNING: Creating illegal content is a serious crime that can result in felony charges, prison time, asset seizure, and permanent criminal records. Users engage in such activities at their own complete risk and responsibility.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold text-white mb-4">6. MAXIMUM LEGAL PROTECTION</h2>
          <div className="bg-gray-800 border border-gray-600 p-6 rounded-lg space-y-4">
            <div>
              <h3 className="text-lg font-semibold text-gray-300 mb-3">Comprehensive Protection Clauses</h3>
              <ul className="list-disc list-inside space-y-2 text-gray-300">
                <li><strong>LIMITATION OF LIABILITY:</strong> Our liability is limited to $0 for any claims</li>
                <li><strong>NO WARRANTY:</strong> All services provided without any warranty whatsoever</li>
                <li><strong>ASSUMPTION OF RISK:</strong> Users assume all risks associated with platform use</li>
                <li><strong>RELEASE OF CLAIMS:</strong> Users release all claims against MEDUSAVR and RINTERIOR</li>
                <li><strong>ARBITRATION CLAUSE:</strong> All disputes subject to binding arbitration</li>
                <li><strong>JURISDICTION:</strong> All legal matters governed by platform-favorable jurisdiction</li>
                <li><strong>SEVERABILITY:</strong> If any clause is invalid, remaining protections remain in full force</li>
              </ul>
            </div>
          </div>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold text-white mb-4">7. USER ACKNOWLEDGMENT REQUIREMENTS</h2>
          <div className="bg-blue-900/20 border border-blue-700 p-6 rounded-lg space-y-4">
            <div>
              <h3 className="text-lg font-semibold text-blue-400 mb-3">Mandatory User Acknowledgments</h3>
              <p className="text-gray-300 mb-3">By using MEDUSAVR, you explicitly acknowledge and agree that:</p>
              <ul className="list-disc list-inside space-y-2 text-gray-300">
                <li>You have read and understood all legal disclaimers and warnings</li>
                <li>You accept complete personal responsibility for all your actions</li>
                <li>You understand the serious legal risks of creating illegal content</li>
                <li>You agree to indemnify and protect MEDUSAVR and RINTERIOR from all claims</li>
                <li>You waive all rights to hold the platform or team liable for your actions</li>
                <li>You understand that we will cooperate with law enforcement against illegal activity</li>
                <li>You accept that you may face serious criminal and civil penalties for violations</li>
                <li>You agree that continued use constitutes ongoing acceptance of these terms</li>
              </ul>
            </div>
          </div>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold text-white mb-4">8. REPORTING AND COOPERATION</h2>
          <div className="bg-purple-900/20 border border-purple-700 p-6 rounded-lg space-y-4">
            <div>
              <h3 className="text-lg font-semibold text-purple-400 mb-3">Law Enforcement Cooperation</h3>
              <ul className="list-disc list-inside space-y-2 text-gray-300">
                <li><strong>MANDATORY REPORTING:</strong> We will report illegal activity to appropriate authorities</li>
                <li><strong>FULL COOPERATION:</strong> We will provide complete cooperation with law enforcement investigations</li>
                <li><strong>USER INFORMATION:</strong> We will provide user information when legally required</li>
                <li><strong>EVIDENCE PRESERVATION:</strong> We will preserve evidence of illegal activity for law enforcement</li>
                <li><strong>NO USER PROTECTION:</strong> We will not protect users from legal consequences of their actions</li>
              </ul>
            </div>
          </div>
        </section>

        <section className="mb-8">
          <div className="bg-green-900/20 border border-green-700 p-6 rounded-lg">
            <h2 className="text-2xl font-bold text-green-400 mb-4">Contact Information</h2>
            <div className="space-y-2 text-gray-300">
              <p><strong>Legal Questions:</strong> <a href="mailto:vrfans11@gmail.com" className="text-green-400 hover:text-green-300">vrfans11@gmail.com</a></p>
              <p><strong>Compliance Issues:</strong> <a href="mailto:vrfans11@gmail.com" className="text-green-400 hover:text-green-300">vrfans11@gmail.com</a></p>
              <p><strong>Emergency Reporting:</strong> <a href="mailto:vrfans11@gmail.com" className="text-green-400 hover:text-green-300">vrfans11@gmail.com</a></p>
            </div>
            <div className="mt-4 p-4 bg-green-800/20 border border-green-600 rounded">
              <p className="text-green-200 font-semibold">
                Remember: You are completely responsible for your actions. Use this platform legally and responsibly.
              </p>
            </div>
          </div>
        </section>
      </div>
    </LegalPolicyPage>
  );
};

export default LiabilityDisclaimerPage;
